#!/usr/bin/env bash
# make-myapp.sh -- scaffold the throwaway `myapp` demo repo the terminal-scenes
# captures record against (plan:terminal-scenes). This repo is NEVER committed to
# the Seamless tree; only this generator is. It is a tiny stdlib-only Go web
# service with exactly the two work surfaces the scenes need:
#
#   - POST /auth/refresh (auth.go) -- the auth-refresh plan's next step (step 5,
#     rate-limiting) is a real, missing thing an agent can add.
#   - an HTML home handler + a static asset handler (server.go) -- scene 2's
#     "HTML responses are slow -- add caching" landmine: the wrong fix caches the
#     HTML, the right fix caches the assets only (edge-cache-gotcha memory).
#
# Usage: scripts/scene-fixture/make-myapp.sh <target-dir>
#   Recreates <target-dir> from scratch and leaves it as a committed git repo.
set -euo pipefail

dir="${1:-}"
if [[ -z "$dir" ]]; then
  echo "usage: $0 <target-dir>" >&2
  exit 2
fi

# Guard: never scaffold over a live checkout. The dir must be absent or a prior
# myapp scaffold (marked by .seamless-scene-fixture).
if [[ -e "$dir" && ! -e "$dir/.seamless-scene-fixture" ]]; then
  echo "make-myapp: $dir exists and is not a scene fixture; refusing to overwrite" >&2
  exit 1
fi
rm -rf "$dir"
mkdir -p "$dir/static"

cat >"$dir/.seamless-scene-fixture" <<'EOF'
Throwaway demo repo generated by scripts/scene-fixture/make-myapp.sh for
plan:terminal-scenes. Safe to delete. Not part of the Seamless source tree.
EOF

cat >"$dir/go.mod" <<'EOF'
module myapp

go 1.21
EOF

cat >"$dir/main.go" <<'EOF'
// myapp is a tiny web service used to demo Seamless. It signs users in with a
// rotating refresh-token scheme and serves a small HTML dashboard.
package main

import (
	"log"
	"net/http"
)

func main() {
	srv := newServer()
	addr := ":8080"
	log.Printf("myapp listening on %s", addr)
	if err := http.ListenAndServe(addr, srv.routes()); err != nil {
		log.Fatal(err)
	}
}
EOF

cat >"$dir/server.go" <<'EOF'
package main

import (
	"html/template"
	"net/http"
)

type server struct {
	tokens *tokenStore
	home   *template.Template
}

func newServer() *server {
	return &server{
		tokens: newTokenStore(),
		home:   template.Must(template.New("home").Parse(homeHTML)),
	}
}

func (s *server) routes() http.Handler {
	mux := http.NewServeMux()
	mux.HandleFunc("/", s.handleHome)
	mux.HandleFunc("/healthz", s.handleHealthz)
	mux.HandleFunc("/auth/refresh", s.handleRefresh)
	// Static assets (JS, CSS) live under /static/ with content-hashed names.
	mux.Handle("/static/", http.StripPrefix("/static/", http.FileServer(http.Dir("static"))))
	return mux
}

// handleHome renders the dashboard HTML. It varies by the session cookie, so its
// response is per-user.
func (s *server) handleHome(w http.ResponseWriter, r *http.Request) {
	if r.URL.Path != "/" {
		http.NotFound(w, r)
		return
	}
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	user := "guest"
	if c, err := r.Cookie("session"); err == nil && c.Value != "" {
		user = "member"
	}
	_ = s.home.Execute(w, map[string]string{"User": user})
}

func (s *server) handleHealthz(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusOK)
	_, _ = w.Write([]byte("ok"))
}

const homeHTML = `<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <title>myapp</title>
  <link rel="stylesheet" href="/static/style.css">
</head>
<body>
  <main>
    <h1>myapp</h1>
    <p>Signed in as: {{.User}}</p>
  </main>
  <script src="/static/app.js"></script>
</body>
</html>`
EOF

cat >"$dir/auth.go" <<'EOF'
package main

import (
	"encoding/json"
	"net/http"
)

// handleRefresh rotates the caller's refresh token: it validates the presented
// token, mints a fresh access+refresh pair, and invalidates the old refresh
// token. A replayed (already-rotated) token means it leaked, so the whole family
// is revoked.
//
// TODO(auth-refresh step 5): this endpoint has no rate limit. A stuffing attack
// can hammer it. Add a per-IP and per-family limiter before the token lookup.
func (s *server) handleRefresh(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodPost {
		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
		return
	}
	c, err := r.Cookie("refresh")
	if err != nil || c.Value == "" {
		http.Error(w, "missing refresh token", http.StatusUnauthorized)
		return
	}
	pair, err := s.tokens.rotate(c.Value)
	if err != nil {
		http.Error(w, "invalid refresh token", http.StatusUnauthorized)
		return
	}
	// Cookies are HttpOnly + Secure + SameSite=Lax; tokens never ride in the body.
	setAuthCookie(w, "session", pair.access)
	setAuthCookie(w, "refresh", pair.refresh)
	w.Header().Set("Content-Type", "application/json")
	_ = json.NewEncoder(w).Encode(map[string]string{"status": "ok"})
}

func setAuthCookie(w http.ResponseWriter, name, value string) {
	http.SetCookie(w, &http.Cookie{
		Name:     name,
		Value:    value,
		Path:     "/",
		HttpOnly: true,
		Secure:   true,
		SameSite: http.SameSiteLaxMode,
	})
}
EOF

cat >"$dir/tokens.go" <<'EOF'
package main

import (
	"crypto/rand"
	"encoding/hex"
	"errors"
	"sync"
)

type tokenPair struct {
	access  string
	refresh string
}

// tokenStore holds refresh-token families in memory. Each family maps its
// current (live) refresh token; presenting a token that is not the live one for
// its family is treated as a replay and revokes the family.
type tokenStore struct {
	mu       sync.Mutex
	familyOf map[string]string // refresh token -> family id
	live     map[string]string // family id -> current live refresh token
}

func newTokenStore() *tokenStore {
	return &tokenStore{
		familyOf: map[string]string{},
		live:     map[string]string{},
	}
}

var errReuse = errors.New("refresh token reuse detected; family revoked")

func (t *tokenStore) rotate(refresh string) (tokenPair, error) {
	t.mu.Lock()
	defer t.mu.Unlock()

	fam, ok := t.familyOf[refresh]
	if !ok {
		return tokenPair{}, errors.New("unknown refresh token")
	}
	if t.live[fam] != refresh {
		// Replay of a rotated token: revoke the whole family.
		t.revokeLocked(fam)
		return tokenPair{}, errReuse
	}
	next := tokenPair{access: mintToken(), refresh: mintToken()}
	delete(t.familyOf, refresh)
	t.familyOf[next.refresh] = fam
	t.live[fam] = next.refresh
	return next, nil
}

func (t *tokenStore) revokeLocked(fam string) {
	for tok, f := range t.familyOf {
		if f == fam {
			delete(t.familyOf, tok)
		}
	}
	delete(t.live, fam)
}

func mintToken() string {
	b := make([]byte, 16)
	_, _ = rand.Read(b)
	return hex.EncodeToString(b)
}
EOF

cat >"$dir/static/style.css" <<'EOF'
body { font-family: system-ui, sans-serif; margin: 2rem; }
h1 { font-weight: 600; }
EOF

cat >"$dir/static/app.js" <<'EOF'
// Refreshes the session in the background before the access token expires.
async function refresh() {
  await fetch('/auth/refresh', { method: 'POST', credentials: 'same-origin' });
}
setInterval(refresh, 10 * 60 * 1000);
EOF

cat >"$dir/README.md" <<'EOF'
# myapp

A small web service: a rotating refresh-token auth flow and an HTML dashboard.

- `auth.go` / `tokens.go` -- the `/auth/refresh` rotation + reuse detection.
- `server.go` -- the HTML home handler and the `/static/` asset handler.

Work in flight lives in the `auth-refresh` plan (see the Seamless briefing).
EOF

cd "$dir"
git init -q
git add -A
git -c user.name='myapp' -c user.email='dev@myapp.local' commit -qm 'myapp: initial scaffold'
echo "make-myapp: scaffolded $dir"
