package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/require"

	"github.com/0spoon/seamless/internal/bench"
)

func TestParseEnvFile(t *testing.T) {
	tests := []struct {
		name    string
		in      string
		want    map[string]string
		wantErr string
	}{
		{
			name: "harness shape",
			in: "# arm \"mechanism\" -- generated by scripts/fixture/harness.sh --mode bench\n" +
				"SEAMBENCH_CONDITION=\"mechanism\"\n" +
				"CLAUDE_CONFIG_DIR=\"/tmp/b/arms/mechanism/home/.claude\"\n" +
				"\n" +
				"SEAMBENCH_PORT=\"8100\"\n",
			want: map[string]string{
				"SEAMBENCH_CONDITION": "mechanism",
				"CLAUDE_CONFIG_DIR":   "/tmp/b/arms/mechanism/home/.claude",
				"SEAMBENCH_PORT":      "8100",
			},
		},
		{
			name: "unquoted, single-quoted and exported values",
			in:   "A=plain\nB='single'\nexport C=\"double\"\n",
			want: map[string]string{"A": "plain", "B": "single", "C": "double"},
		},
		{
			name: "empty value stays empty",
			in:   "SEAMBENCH_MODEL=\"\"\n",
			want: map[string]string{"SEAMBENCH_MODEL": ""},
		},
		{
			name:    "a non-assignment line is drift, not noise",
			in:      "SEAMBENCH_CONDITION=\"vanilla\"\nserve the arm\n",
			wantErr: "line 2",
		},
		{
			name:    "a bad variable name is rejected",
			in:      "2BAD=\"x\"\n",
			wantErr: "not a KEY",
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, err := parseEnvFile(strings.NewReader(tt.in))
			if tt.wantErr != "" {
				require.ErrorContains(t, err, tt.wantErr)
				return
			}
			require.NoError(t, err)
			require.Equal(t, tt.want, got)
		})
	}
}

func TestLoadArm_SeamlessAndVanilla(t *testing.T) {
	base := t.TempDir()
	mech := bench.Condition{Name: "mechanism", Profile: bench.ProfileMechanism, Client: bench.ClientClaude}
	vanilla := bench.Condition{Name: "vanilla", Profile: bench.ProfileVanilla, Client: bench.ClientClaude}
	fm := newArmFixture(t, base, mech, 8099)
	fv := newArmFixture(t, base, vanilla, 0)

	a, err := loadArm(armEnvPath(base, "mechanism"), mech)
	require.NoError(t, err)
	require.True(t, a.seamless)
	require.Equal(t, fm.configDir, a.configDir)
	require.Equal(t, "CLAUDE_CONFIG_DIR", a.configEnv)
	require.Equal(t, fm.repo, a.repo)
	require.Equal(t, fm.dataDir, a.dataDir)
	require.Equal(t, fm.config, a.config)
	require.Equal(t, "http://127.0.0.1:8099", a.url)
	require.Equal(t, fixtureModel, a.model)
	require.Equal(t, fm.dir, a.dir)

	key, err := a.key()
	require.NoError(t, err)
	require.Equal(t, fixtureKey, key)

	v, err := loadArm(armEnvPath(base, "vanilla"), vanilla)
	require.NoError(t, err)
	require.False(t, v.seamless)
	require.Empty(t, v.config)
	require.Empty(t, v.dataDir)
	require.Equal(t, fv.repo, v.repo)
}

func TestLoadArm_RejectsDriftAndMissingKeys(t *testing.T) {
	base := t.TempDir()
	cond := bench.Condition{Name: "mechanism", Profile: bench.ProfileMechanism, Client: bench.ClientClaude}
	f := newArmFixture(t, base, cond, 8099)

	// The arm on disk describes a different condition than the one requested.
	_, err := loadArm(f.envFile, bench.Condition{Name: "mechanism", Profile: bench.ProfileFull, Client: bench.ClientClaude})
	require.ErrorContains(t, err, "SEAMBENCH_PROFILE")

	// A Seamless-ful arm missing its data dir is unusable.
	body, err := os.ReadFile(f.envFile)
	require.NoError(t, err)
	trimmed := strings.ReplaceAll(string(body), `SEAMBENCH_DATA_DIR="`+f.dataDir+`"`+"\n", "")
	require.NoError(t, os.WriteFile(f.envFile, []byte(trimmed), 0o644))
	_, err = loadArm(f.envFile, cond)
	require.ErrorContains(t, err, "SEAMBENCH_DATA_DIR")

	// A missing env file names the condition it belonged to.
	_, err = loadArm(filepath.Join(base, "arms", "nope", "env"), bench.Condition{Name: "nope", Profile: bench.ProfileVanilla, Client: bench.ClientClaude})
	require.ErrorContains(t, err, "condition nope")
}

func TestArmEnv_ScrubsLiveStatePointers(t *testing.T) {
	base := t.TempDir()
	vanilla := bench.Condition{Name: "vanilla", Profile: bench.ProfileVanilla, Client: bench.ClientClaude}
	newArmFixture(t, base, vanilla, 0)
	a, err := loadArm(armEnvPath(base, "vanilla"), vanilla)
	require.NoError(t, err)

	t.Setenv("SEAMLESS_CONFIG", "/live/seamless.yaml")
	t.Setenv("CLAUDE_CONFIG_DIR", "/live/.claude")
	t.Setenv("CODEX_HOME", "/live/.codex")
	t.Setenv("SEAMBENCH_CONDITION", "leaked")
	t.Setenv("PATH_MARKER_FOR_TEST", "kept")

	env := a.agentEnv()
	require.Contains(t, env, "HOME="+a.home)
	require.Contains(t, env, "CLAUDE_CONFIG_DIR="+a.configDir)
	require.Contains(t, env, "PATH_MARKER_FOR_TEST=kept")
	for _, kv := range env {
		require.NotEqual(t, "SEAMLESS_CONFIG=/live/seamless.yaml", kv)
		require.NotEqual(t, "CODEX_HOME=/live/.codex", kv)
		require.NotEqual(t, "SEAMBENCH_CONDITION=leaked", kv)
		require.False(t, strings.HasPrefix(kv, "SEAMLESS_"), "vanilla arm must carry no SEAMLESS_ var: %s", kv)
	}
}
