package main

import (
	"bytes"
	"embed"
	"fmt"
	"html/template"
	"os"
	"path/filepath"
	"strings"
)

//go:embed templates
var templateFS embed.FS

// generatedMarker is stamped into every emitted HTML file. It tells a reader the
// file is not editable by hand, and it is the safety interlock for writeSite's
// clean step: a directory whose index.html lacks the marker is not ours to
// delete. Without that check a mistyped -out (say `-out docs`) would RemoveAll
// the landing page, CNAME, and fonts.
const generatedMarker = "<!-- generated by docsgen; edit docs-src/ -->"

// templates are parsed once. Each page template supplies the "content" block the
// layout wraps, mirroring internal/console's render pattern.
var templates = func() map[string]*template.Template {
	out := make(map[string]*template.Template)
	for _, name := range []string{"home", "section", "page"} {
		out[name] = template.Must(template.ParseFS(templateFS,
			"templates/layout.html", "templates/"+name+".html"))
	}
	return out
}()

// pageView is what a template receives: the page plus the site it belongs to
// (for the sidebar) -- the two things every template needs and nothing else.
type pageView struct {
	*Page
	Site *Site
}

// renderPages fills in each page's Body, Headings, and Text. Generated pages get
// their generator's markdown appended to the authored body first, so generated
// content flows through the same pipeline as prose and inherits heading anchors,
// the TOC, and search indexing for free.
func renderPages(site *Site) error {
	for _, p := range site.Pages {
		md := p.Markdown
		if p.Generate != "" {
			extra, err := generate(p.Generate, p, site.SrcDir)
			if err != nil {
				return fmt.Errorf("%s: generate %q: %w", p.Src, p.Generate, err)
			}
			md = strings.TrimRight(md, "\n") + "\n\n" + extra
		}
		out, err := renderMarkdown(md, p.DocsRoot)
		if err != nil {
			return fmt.Errorf("%s: %w", p.Src, err)
		}
		p.Body, p.Headings, p.Links, p.Text = out.HTML, out.Headings, out.Links, plainText(md)
	}
	return checkLinks(site)
}

// checkLinks resolves every internal link against the site. A cross-reference to
// a page that does not exist (or whose URL changed) still renders as a link --
// it just goes nowhere -- so nothing but a build error catches it before a
// reader does.
func checkLinks(site *Site) error {
	pages := make(map[string]bool, len(site.Pages))
	for _, p := range site.Pages {
		pages["/"+p.URL] = true
	}
	var broken []string
	for _, p := range site.Pages {
		for _, link := range p.Links {
			target, _, _ := strings.Cut(link, "#")
			if target == "" || pages[target] || strings.HasPrefix(target, "/static/") {
				continue
			}
			broken = append(broken, fmt.Sprintf("%s -> %s", p.Src, link))
		}
	}
	if len(broken) > 0 {
		return fmt.Errorf("links to pages that do not exist:\n  %s", strings.Join(broken, "\n  "))
	}
	return nil
}

// writeSite replaces outDir with the rendered site.
func writeSite(outDir string, site *Site) error {
	if err := cleanOutput(outDir); err != nil {
		return err
	}
	for _, p := range site.Pages {
		html, err := renderPage(site, p)
		if err != nil {
			return err
		}
		if err := writeFile(filepath.Join(outDir, filepath.FromSlash(p.Out)), html); err != nil {
			return err
		}
	}
	if err := writeAssets(outDir); err != nil {
		return err
	}
	return writeSearchIndex(outDir, site)
}

func renderPage(site *Site, p *Page) ([]byte, error) {
	tmpl, ok := templates[p.Template]
	if !ok {
		return nil, fmt.Errorf("%s: unknown template %q", p.Out, p.Template)
	}
	var buf bytes.Buffer
	buf.WriteString(generatedMarker + "\n")
	if err := tmpl.ExecuteTemplate(&buf, "layout", pageView{Page: p, Site: site}); err != nil {
		return nil, fmt.Errorf("%s: %w", p.Out, err)
	}
	return buf.Bytes(), nil
}

// cleanOutput removes a previously generated tree, refusing to touch a directory
// that does not look like one of ours.
func cleanOutput(outDir string) error {
	entries, err := os.ReadDir(outDir)
	if os.IsNotExist(err) {
		return nil
	}
	if err != nil {
		return fmt.Errorf("read %s: %w", outDir, err)
	}
	if len(entries) == 0 {
		return nil
	}
	index := filepath.Join(outDir, "index.html")
	raw, err := os.ReadFile(index)
	if err != nil || !bytes.Contains(raw, []byte(generatedMarker)) {
		return fmt.Errorf("refusing to replace %s: %s is missing or was not generated by docsgen "+
			"(delete the directory by hand if this is really the output dir)", outDir, index)
	}
	if err := os.RemoveAll(outDir); err != nil {
		return fmt.Errorf("clean %s: %w", outDir, err)
	}
	return nil
}

func writeFile(path string, content []byte) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("mkdir %s: %w", filepath.Dir(path), err)
	}
	if err := os.WriteFile(path, content, 0o644); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	return nil
}
