#!/bin/sh
# changelog: regenerate docs-src/changelog.md from the git tags, newest first.
#
# RUN AT RELEASE TIME, via `make changelog`, after the new v* tag exists. This
# is deliberately a separate step OUTSIDE the docsgen render: a release date is
# real wall-clock data, and the docsgen output must be byte-deterministic
# (TestRenderIsDeterministic, `make docs-check`) -- a date injected during
# `make docs` would make the committed site drift on every unrelated PR. Here
# the dates enter a committed *source* page instead, which the determinism
# tripwire (TestOutputHasNoBuildTimestamp) explicitly exempts: a date the
# sources contain is content, not a build stamp.
#
# The output depends only on the tags and the commit history, so re-running at
# the same commit is byte-identical -- idempotent by construction, like docsgen.
#
# The entries mirror the GitHub release notes goreleaser builds (see the
# `changelog:` block in .goreleaser.yaml): commit subjects since the previous
# tag, grouped Features (^feat) / Fixes (^fix) / Other, with ^docs, ^chore,
# ^ci, and ^test excluded. Keep the two in step: someone reading the page and
# someone reading the release must see the same story.

set -eu

OUT="docs-src/changelog.md"
REPO_URL="https://github.com/0spoon/seamless"
MODE="write"
case "${1:-}" in
	"") ;;
	--check) MODE="check" ;;
	*) echo "usage: scripts/changelog.sh [--check]" >&2; exit 2 ;;
esac

# Tag dates are formatted in UTC so the page does not depend on the timezone of
# whoever cut the release.
TZ=UTC
export TZ

[ -f go.mod ] || { echo "ERROR: run from the repository root (try 'make changelog')" >&2; exit 1; }

tags=$(git tag --list 'v*' --sort=-v:refname)
[ -n "$tags" ] || { echo "ERROR: no v* tags -- nothing to generate a changelog from" >&2; exit 1; }

# Commit subjects become markdown in a renderer that allows raw HTML, where an
# unknown element like <slug> silently renders as nothing -- the same reason
# docsgen escapes generated text (generators.go escapeText).
escape() {
	sed 's/&/\&amp;/g; s/</\&lt;/g; s/>/\&gt;/g'
}

# group <title> <subjects...>: emit one "### title" bullet list, or nothing.
group() {
	title=$1
	subjects=$2
	[ -n "$subjects" ] || return 0
	printf '### %s\n\n' "$title"
	printf '%s\n' "$subjects" | escape | sed 's/^/- /'
	printf '\n'
}

tmp=$(mktemp)
trap 'rm -f "$tmp"' EXIT

{
	cat <<'EOF'
---
title: Changelog
description: Every Seamless release, newest first - what shipped and when, regenerated from the git tags at each release.
---

<!-- GENERATED by scripts/changelog.sh (make changelog) from the git tags.
     Do not edit by hand: edit the script, or for release notes themselves,
     write better commit subjects. -->

Every release, newest first. The entries mirror the notes on
[GitHub Releases](https://github.com/0spoon/seamless/releases) - the same
commit subjects, grouped the same way, with housekeeping (docs, CI, dependency
bumps) filtered out. Each heading links the release's downloads and checksums.

Install with one command ([quickstart](/quickstart/)), or update an existing
install in place with `seamlessd update`.

EOF

	for tag in $tags; do
		date=$(git for-each-ref "refs/tags/$tag" --format='%(creatordate:format-local:%Y-%m-%d)')
		anchor=$(printf '%s' "$tag" | tr '.' '-')
		prev=$(printf '%s\n' "$tags" | awk -v t="$tag" 'f { print; exit } $0 == t { f = 1 }')

		printf '## %s {#%s}\n\n' "$tag" "$anchor"
		printf 'Released %s - [downloads and notes](%s/releases/tag/%s)\n\n' \
			"$date" "$REPO_URL" "$tag"

		if [ -z "$prev" ]; then
			printf 'The first public release of Seamless.\n\n'
			continue
		fi

		subjects=$(git log --no-merges --pretty=format:'%s' "$prev..$tag")
		if [ -z "$subjects" ]; then
			printf 'No source changes since %s.\n\n' "$prev"
			continue
		fi

		features=$(printf '%s\n' "$subjects" | grep -E '^feat' || true)
		fixes=$(printf '%s\n' "$subjects" | grep -E '^fix' || true)
		other=$(printf '%s\n' "$subjects" | grep -Ev '^(feat|fix|docs|chore|ci|test)' || true)

		if [ -z "$features$fixes$other" ]; then
			printf 'Documentation, CI, and dependency maintenance only.\n\n'
			continue
		fi

		group "Features" "$features"
		group "Fixes" "$fixes"
		group "Other" "$other"
	done
} >"$tmp"

count=$(printf '%s\n' "$tags" | wc -l | tr -d ' ')
newest=$(printf '%s\n' "$tags" | head -1)
if [ "$MODE" = "check" ]; then
	if ! cmp -s "$tmp" "$OUT"; then
		echo "changelog drift: $OUT does not include the current tag history (run 'make changelog')" >&2
		diff -u "$OUT" "$tmp" | sed -n '1,80p' >&2 || true
		exit 1
	fi
	echo "changelog-check: $OUT covers $count releases through $newest"
else
	mv "$tmp" "$OUT"
	echo "changelog: wrote $OUT ($count releases, newest $newest)"
fi
