package config

import (
	"crypto/rand"
	"encoding/hex"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
)

// EnsureAPIKey makes a true first run self-configuring: when no config file
// exists anywhere in the search order and SEAMLESS_MCP_API_KEY is absent from
// the environment, it generates a bearer key, writes it to
// ~/.config/seamless/seamless.yaml (0600), and returns the updated config plus
// the path it wrote. In every other case it changes nothing and returns "":
// a key already set, an owner-authored config file (even one with an empty
// key), or an env override (even set-but-empty) are never edited on the
// owner's behalf -- the existing empty-key warning paths stay in charge there.
func EnsureAPIKey(cfg Config) (Config, string, error) {
	if cfg.MCP.APIKey != "" || cfg.SourcePath() != "" {
		return cfg, "", nil
	}
	if _, set := os.LookupEnv("SEAMLESS_MCP_API_KEY"); set {
		return cfg, "", nil
	}

	home, err := os.UserHomeDir()
	if err != nil {
		return cfg, "", fmt.Errorf("config.EnsureAPIKey: %w", err)
	}
	path := filepath.Join(home, ".config", "seamless", "seamless.yaml")
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		return cfg, "", fmt.Errorf("config.EnsureAPIKey: %w", err)
	}

	buf := make([]byte, 32)
	if _, err := rand.Read(buf); err != nil {
		return cfg, "", fmt.Errorf("config.EnsureAPIKey: generate key: %w", err)
	}
	key := hex.EncodeToString(buf)

	// O_EXCL: if another process bootstrapped between our Load and now, its
	// file wins -- load it instead of clobbering the key agents already hold.
	f, err := os.OpenFile(path, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0o600)
	if err != nil {
		if errors.Is(err, fs.ErrExist) {
			loaded, lerr := LoadFrom(path)
			if lerr != nil {
				return cfg, "", fmt.Errorf("config.EnsureAPIKey: %w", lerr)
			}
			return loaded, "", nil
		}
		return cfg, "", fmt.Errorf("config.EnsureAPIKey: %w", err)
	}
	content := "# Generated by seamlessd on first run. Every key, its default, and its\n" +
		"# SEAMLESS_* env override: see seamless.yaml.example in the repo or\n" +
		"# /docs/reference/configuration/ on the docs site.\n" +
		"mcp:\n" +
		"  # Static bearer key protecting /api/mcp and the console.\n" +
		"  # env: SEAMLESS_MCP_API_KEY\n" +
		"  api_key: \"" + key + "\"\n"
	if _, err := f.WriteString(content); err != nil {
		_ = f.Close()
		return cfg, "", fmt.Errorf("config.EnsureAPIKey: write %s: %w", path, err)
	}
	if err := f.Sync(); err != nil {
		_ = f.Close()
		return cfg, "", fmt.Errorf("config.EnsureAPIKey: sync %s: %w", path, err)
	}
	if err := f.Close(); err != nil {
		return cfg, "", fmt.Errorf("config.EnsureAPIKey: close %s: %w", path, err)
	}

	cfg.MCP.APIKey = key
	cfg.sourcePath = path
	return cfg, path, nil
}
