package config

import (
	"crypto/rand"
	"encoding/hex"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"strconv"
	"strings"
)

// envMCPAPIKey is the environment override for mcp.api_key. Both bootstrap
// paths consult it -- EnsureAPIKey to decide whether a key is needed at all,
// EnsureClientConfig to resolve which key to write -- so the two cannot drift
// onto different spellings of the same variable.
const envMCPAPIKey = "SEAMLESS_MCP_API_KEY"

// envServerURL is the environment override for server_url (applyEnv wires it to
// AdvertisedURL). EnsureClientConfig reads it to refuse a client install whose
// flag and environment name different servers.
const envServerURL = "SEAMLESS_SERVER_URL"

// EnsureAPIKey makes a true first run self-configuring: when no config file
// exists anywhere in the search order and SEAMLESS_MCP_API_KEY is absent from
// the environment, it generates a bearer key, writes it to
// ~/.config/seamless/seamless.yaml (0600), and returns the updated config plus
// the path it wrote. In every other case it changes nothing and returns "":
// a key already set, an owner-authored config file (even one with an empty
// key), or an env override (even set-but-empty) are never edited on the
// owner's behalf -- the existing empty-key warning paths stay in charge there.
func EnsureAPIKey(cfg Config) (Config, string, error) {
	if cfg.MCP.APIKey != "" || cfg.SourcePath() != "" {
		return cfg, "", nil
	}
	if _, set := os.LookupEnv(envMCPAPIKey); set {
		return cfg, "", nil
	}

	home, err := os.UserHomeDir()
	if err != nil {
		return cfg, "", fmt.Errorf("config.EnsureAPIKey: %w", err)
	}
	path := filepath.Join(home, ".config", "seamless", "seamless.yaml")
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		return cfg, "", fmt.Errorf("config.EnsureAPIKey: %w", err)
	}

	buf := make([]byte, 32)
	if _, err := rand.Read(buf); err != nil {
		return cfg, "", fmt.Errorf("config.EnsureAPIKey: generate key: %w", err)
	}
	key := hex.EncodeToString(buf)

	// O_EXCL: if another process bootstrapped between our Load and now, its
	// file wins -- load it instead of clobbering the key agents already hold.
	f, err := os.OpenFile(path, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0o600)
	if err != nil {
		if errors.Is(err, fs.ErrExist) {
			loaded, lerr := LoadFrom(path)
			if lerr != nil {
				return cfg, "", fmt.Errorf("config.EnsureAPIKey: %w", lerr)
			}
			return loaded, "", nil
		}
		return cfg, "", fmt.Errorf("config.EnsureAPIKey: %w", err)
	}
	content := "# Generated by seamlessd on first run. Every key, its default, and its\n" +
		"# SEAMLESS_* env override: see seamless.yaml.example in the repo or\n" +
		"# /docs/reference/configuration/ on the docs site.\n" +
		"mcp:\n" +
		"  # Static bearer key protecting /api/mcp and the console.\n" +
		"  # env: SEAMLESS_MCP_API_KEY\n" +
		"  api_key: \"" + key + "\"\n"
	if _, err := f.WriteString(content); err != nil {
		_ = f.Close()
		return cfg, "", fmt.Errorf("config.EnsureAPIKey: write %s: %w", path, err)
	}
	if err := f.Sync(); err != nil {
		_ = f.Close()
		return cfg, "", fmt.Errorf("config.EnsureAPIKey: sync %s: %w", path, err)
	}
	if err := f.Close(); err != nil {
		return cfg, "", fmt.Errorf("config.EnsureAPIKey: close %s: %w", path, err)
	}

	cfg.MCP.APIKey = key
	cfg.sourcePath = path
	return cfg, path, nil
}

// EnsureClientConfig writes the config file that makes THIS machine a client of
// a seamlessd running somewhere else: `role: client`, the `server_url` clients
// dial, and the bearer key that server issued. It is `install-hooks
// --server-url`'s first-run step, and it returns the loaded result plus the path
// it wrote ("" when it wrote nothing).
//
// It refuses in exactly the ways EnsureAPIKey refuses, for the same reason --
// the config file is the owner's, and a bootstrap that edits one is a bootstrap
// that can silently repoint an install:
//
//   - A config file anywhere in the search order is NEVER edited. The error
//     names the file and the exact lines to add by hand. The one file that is
//     not an error is one that already says exactly this (sameClientConfig):
//     nothing is written there either, but there is also nothing to complain
//     about, which is what keeps re-running the installer from failing.
//   - The create is O_EXCL 0600, so a process that bootstrapped between the
//     search and the create keeps its file. An identical client config is that
//     race resolving in agreement and is returned as the winner; anything else
//     is the same refusal, because silently adopting a file that points
//     somewhere else would wire this machine to the wrong server.
//   - No key is generated. A client's key belongs to the server it dials, so
//     there is nothing valid to invent: the key comes from the key argument
//     (--api-key), else from SEAMLESS_MCP_API_KEY, and neither present is an
//     error rather than a config that cannot authenticate.
//
// There is deliberately no data_dir: a client holds no corpus and opens no
// database.
func EnsureClientConfig(url, key string) (Config, string, error) {
	serverURL, err := clientServerURL(url)
	if err != nil {
		return Config{}, "", fmt.Errorf("config.EnsureClientConfig: %w", err)
	}
	apiKey, keySource, err := clientAPIKey(key)
	if err != nil {
		return Config{}, "", fmt.Errorf("config.EnsureClientConfig: %w", err)
	}

	existing, err := findConfigFile()
	if err != nil {
		return Config{}, "", fmt.Errorf("config.EnsureClientConfig: %w", err)
	}
	if existing != "" {
		loaded, aerr := adoptExistingConfig(existing, serverURL, apiKey, keySource)
		return loaded, "", aerr
	}

	home, err := os.UserHomeDir()
	if err != nil {
		return Config{}, "", fmt.Errorf("config.EnsureClientConfig: %w", err)
	}
	path := filepath.Join(home, ".config", "seamless", "seamless.yaml")
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		return Config{}, "", fmt.Errorf("config.EnsureClientConfig: %w", err)
	}

	f, err := os.OpenFile(path, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0o600)
	if err != nil {
		if errors.Is(err, fs.ErrExist) {
			// Another process won the race. Its file stands either way; the only
			// question is whether it says the same thing ours would have.
			loaded, aerr := adoptExistingConfig(path, serverURL, apiKey, keySource)
			return loaded, "", aerr
		}
		return Config{}, "", fmt.Errorf("config.EnsureClientConfig: %w", err)
	}
	content := "# Generated by seamlessd install-hooks --server-url on first run. Every key,\n" +
		"# its default, and its SEAMLESS_* env override: see seamless.yaml.example in\n" +
		"# the repo or /docs/reference/configuration/ on the docs site.\n" +
		"#\n" +
		"# role: client means this machine runs no daemon of its own: every surface\n" +
		"# dials server_url instead, so there is no data_dir here -- the corpus, the\n" +
		"# database, and the gardener all live on the server.\n" +
		"role: client\n" +
		"# Base URL of the seamlessd this machine dials.\n" +
		"# env: SEAMLESS_SERVER_URL\n" +
		"server_url: " + yamlString(serverURL) + "\n" +
		"mcp:\n" +
		"  # The server's static bearer key, copied from it verbatim.\n" +
		"  # env: SEAMLESS_MCP_API_KEY\n" +
		"  api_key: " + yamlString(apiKey) + "\n"
	if _, err := f.WriteString(content); err != nil {
		_ = f.Close()
		return Config{}, "", fmt.Errorf("config.EnsureClientConfig: write %s: %w", path, err)
	}
	if err := f.Sync(); err != nil {
		_ = f.Close()
		return Config{}, "", fmt.Errorf("config.EnsureClientConfig: sync %s: %w", path, err)
	}
	if err := f.Close(); err != nil {
		return Config{}, "", fmt.Errorf("config.EnsureClientConfig: close %s: %w", path, err)
	}

	// Load what was just written rather than assembling a Config here, so the
	// caller wires hooks against the config every later process will see --
	// including an env override that wins over this file.
	loaded, err := LoadFrom(path)
	if err != nil {
		return Config{}, "", fmt.Errorf("config.EnsureClientConfig: %w", err)
	}
	return loaded, path, nil
}

// clientServerURL normalizes and validates the server a client dials, and
// refuses the one shape that would install a machine against two servers at
// once: a SEAMLESS_SERVER_URL naming somewhere else. That variable overrides the
// file at every later Load, so the hooks written now would point at the flag's
// server while `seam` -- and the hooks' own runtime config resolution -- went to
// the environment's.
func clientServerURL(raw string) (string, error) {
	serverURL := strings.TrimSuffix(strings.TrimSpace(raw), "/")
	if serverURL == "" {
		return "", errors.New("server URL is required (--server-url https://host:8081)")
	}
	if err := validateServerURL(serverURL); err != nil {
		return "", err
	}
	if env, ok := os.LookupEnv(envServerURL); ok {
		if env := strings.TrimSuffix(strings.TrimSpace(env), "/"); env != "" && env != serverURL {
			return "", fmt.Errorf("--server-url %s and %s=%s name different servers: drop one", serverURL, envServerURL, env)
		}
	}
	return serverURL, nil
}

// clientAPIKey resolves which bearer key the client config carries, and names
// where it came from (for the refusal message, which must never print the key
// itself -- an error ends up in terminals, CI logs, and bug reports).
//
// Precedence is the argument (--api-key) over the environment, the same
// direction every other flag-vs-env pair in the CLI runs. A set-but-EMPTY
// SEAMLESS_MCP_API_KEY is an error in both branches, not an absence: env wins
// over file at every later Load, so an empty one would blank the key of the
// file being written here and the install would authenticate nowhere.
func clientAPIKey(flagKey string) (key, source string, err error) {
	flagKey = strings.TrimSpace(flagKey)
	env, envSet := os.LookupEnv(envMCPAPIKey)
	env = strings.TrimSpace(env)
	switch {
	case envSet && env == "":
		return "", "", fmt.Errorf("%s is set but empty: unset it, or set it to the server's mcp.api_key", envMCPAPIKey)
	case flagKey == "" && !envSet:
		return "", "", fmt.Errorf("no bearer key: pass --api-key, or set %s to the server's mcp.api_key (`seamlessd client-config` prints it there)", envMCPAPIKey)
	case flagKey == "":
		return env, envMCPAPIKey, nil
	case envSet && env != flagKey:
		// Present-but-contradictory input, never a silent pick: the file would
		// carry one key and every later Load would override it with the other.
		return "", "", fmt.Errorf("--api-key and %s are both set to different keys: drop one", envMCPAPIKey)
	default:
		return flagKey, "--api-key", nil
	}
}

// adoptExistingConfig decides what a config file that is already there means: a
// file that already says exactly this is adopted (nothing to write, no
// complaint), and anything else is the refusal. The search-order check and the
// O_EXCL race both land here, so the two can never answer differently.
func adoptExistingConfig(path, serverURL, apiKey, keySource string) (Config, error) {
	loaded, err := LoadFrom(path)
	if err != nil {
		return Config{}, fmt.Errorf("config.EnsureClientConfig: %w", err)
	}
	if sameClientConfig(loaded, serverURL, apiKey) {
		return loaded, nil
	}
	return Config{}, existingConfigRefusal(path, serverURL, keySource)
}

// sameClientConfig reports whether a config file that is already there says
// exactly what EnsureClientConfig would have written.
//
// This is what makes a re-run idempotent rather than fatal -- upgrading is
// "install-hooks again", and a client that refused its own settings could only
// ever be installed once. It is not a weakening of the never-edit rule: nothing
// is written either way; agreement is the case where there is nothing to write.
// Any disagreement (a server-role file, another server, another key) is still
// the refusal, because each of those would wire this machine somewhere the
// caller did not ask for.
func sameClientConfig(loaded Config, serverURL, apiKey string) bool {
	return loaded.IsClient() && loaded.ServerURL() == serverURL && loaded.MCP.APIKey == apiKey
}

// existingConfigRefusal is the "your config file, your edit" error: it names the
// file in the way and the three settings that turn it into a client config. The
// key is referred to by its source rather than printed.
func existingConfigRefusal(path, serverURL, keySource string) error {
	return fmt.Errorf("config.EnsureClientConfig: %s already exists and is never edited on your behalf; add these settings to it yourself:\n"+
		"  role: client\n"+
		"  server_url: %s\n"+
		"  mcp:\n"+
		"    api_key: <the key from %s>",
		path, yamlString(serverURL), keySource)
}

// yamlString renders s as a double-quoted YAML scalar. Quoting is not
// cosmetic: an unquoted all-digit api_key would decode as an integer and fail
// the load, and the quoted form is what keeps a hand-picked key from having to
// be a safe plain scalar. Go's escapes are a subset of YAML's double-quoted
// escapes, so strconv.Quote is exactly the right encoder here.
func yamlString(s string) string {
	return strconv.Quote(s)
}
